# Ubuntu Mono (Nerd patch) seems to be the closest to Bront which is wrongly
# patched
font:
  size: 15
  normal:
    #family: "JetBrainsMono Nerd Font"
    #    family: "Bront Nerd Font"
    #family: "DejaVuSans Mono Nerd Font Mono"
    #style: "Book"
    family: "UbuntuMono Nerd Font Mono"
    style: "Regular"
  bold:
    #    family: "JetBrainsMono Nerd Font"
    #    style: "Medium"
    family: "UbuntuMono Nerd Font Mono"
    style: "Regular"

colors:
  # Cursor colors
  cursor:
    text: "0xFFFFFF"
    cursor: "0xe91e63"
  vi_mode_cursor:
    text: "0xFFFFFF"
    cursor: "0xffa500"

  # Default colors
  primary:
    background: "0x32374d"
    foreground: "0xd0d0d0"

  # Normal colors
  normal:
    black: "0x141228"
    red: "0xff5458"
    green: "0x62d196"
    yellow: "0xffb378"
    blue: "0x65b2ff"
    magenta: "0x906cff"
    cyan: "0x63f2f1"
    white: "0xa6b3cc"
  # Bright colors
  bright:
    black: "0x565575"
    red: "0xff8080"
    green: "0x95ffa4"
    yellow: "0xffe9aa"
    blue: "0x91ddff"
    magenta: "0xc991e1"
    cyan: "0xaaffe4"
    white: "0xcbe3e7"
